<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ExcelDataReader" Version="3.8.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.8.0" />
    <PackageReference Include="HtmlRenderer.WinForms" Version="1.5.2" />
    <PackageReference Include="MiniExcel" Version="1.42.0" />
    <PackageReference Include="Obfuscar" Version="2.2.50">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ScottPlot.WinForms" Version="5.1.57" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModbusPilot.Core\ModbusPilot.Core.csproj" />
  </ItemGroup>

</Project>
